demo-rails/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index' 

  # Đường dẫn mặc định localhost:3000 
  # sẽ gọi đến function index trong welcome controller
  root 'welcome#index'

  # rails cung cấp method resources
  resources :articles do 
    resources :comments
  end

  # có thể dùng router tự tạo thay vì method resources của rails
  get 'demo' => 'welcome#demo_render' # gọi đền function demo_render 
                                      # trong welcome_controller

end

demo-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demo-rails/app/models/article.rb
class Article < ApplicationRecord
    # Một bài viết có nhiều comment
    has_many :comments, dependent: :destroy
    # sử dụng dependent destroy 
    # Khi xóa 1 bài viết sẽ tự động xóa các comments của nó

    validates :title, length: { minimum: 5, :message => "phải nhiều hơn 5 ký tự" }
    validates_presence_of  :title,:message => "không được để trống"               
    # Validate title, bắt buộc phải có, và độ dài chuỗi nhỏ nhất = 5
end

demo-rails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

demo-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

demo-rails/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    layout 'article'
    # function hiển thị form post bài viết
    def new
        @article = Article.new
    end

    # function thêm mới bài viết
    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    
    # hiển thị chi tiết bài viết theo id
    def show
        @article = Article.find(params[:id])
    end

    # Hiển thị danh sách bài viết
    def index
        @articles = Article.all # lấy tất cả bài viết đang có
    end

    # hiển thị trang sửa bài viết
    def edit
        @article = Article.find(params[:id])
    end
    # update thông tin bài viết
    def update 
        @article = Article.find(params[:id])
        
        # Kiểm tra nếu update thành công thì chuyển qua trang chi tiết
        if @article.update_attributes(article_params)
            redirect_to @article
        else # nếu không thành công thì quay lại trang edit
            render 'edit'
        end
    end 

    # Xóa bài viết
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
    
        redirect_to articles_path
    end

    private
        def article_params
            # chỉ nhận param title và text
            params.require(:article).permit(:title, :text)
        end
end

demo-rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
     
    private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

demo-rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  # demo render
  def demo_render
    render :layout => 'welcome'
  end
end

demo-rails/app/helpers/acticles_helper.rb
module ActiclesHelper
end

demo-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

demo-rails/app/helpers/articles_helper.rb
module ArticlesHelper
end

demo-rails/app/helpers/comments_helper.rb
module CommentsHelper
end

demo-rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

demo-rails/app/views/articles/_form.html.erb
<%= form_for @article  do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

demo-rails/app/views/articles/edit.html.erb
<h1>Sửa bài viết </h1>
    <%=  render 'form' %>
<%= link_to 'Back', articles_path %>

demo-rails/app/views/articles/index.html.erb
<h1>Danh sách bài viết </h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Thêm bài viết', new_article_path %>

demo-rails/app/views/articles/new.html.erb
<h1>Thêm bài viết</h1>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "lỗi") %> xảy ra:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%=  render 'form' %> <%# render đến file _form.html.erb%>
<%= link_to 'Back', articles_path %>

demo-rails/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>

demo-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :css %>
  </head>

  <body>
    <h1>Hello ruby on rails </h1>
    <%= yield %>
    <%= yield :body %>
  </body>
</html>

demo-rails/app/views/layouts/article.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My layout</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>My layout </h1>
    <%= yield %>
  </body>
</html>

demo-rails/app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My layout</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Welcome to ROR </h1>
    <%= yield %>
  </body>
</html>

demo-rails/app/views/welcome/index.html.erb
<% content_for :css do %>
    <style>
        h1 {
            color: red;
        }
    </style>
<% end %>
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<% content_for :body do %>
    <h3>Nội dung cho yield :body</h3>
<% end %>